homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Media
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
      allow_bypass_login: true
    - type: homeassistant

http:
  base_url: https://automation.prettybaked.com
  
frontend:

config:

view_event:

media_player:  !include_dir_list media_players
apple_tv: !include_dir_list apple_tvs
remote: !include_dir_list remotes
cast:
  media_player: !include_dir_list google_casts
