homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Media
  auth_providers:
    - type: homeassistant
    # - type: trusted_networks
    #   trusted_networks:
    #     - 172.19.0.0/16
    #     - 10.0.12.0/24

http:

frontend:

view_event:

media_player:  !include_dir_list media_players
apple_tv: !include_dir_list apple_tvs
remote: !include_dir_list remotes
cast:
  media_player: !include_dir_list google_casts
