homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Media
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

# view_event:
#   name: media
#   components:
#     - spotify
#     - media_player
#     - appletv
#     - cast
#     - remote

http:
  base_url: http://media.constructorfleet.iot

frontend:

config:

media_player:  !include_dir_list media_players
# apple_tv: !include_dir_list apple_tvs
remote: !include_dir_list remotes
cast:
  media_player: !include_dir_list google_casts

mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
#mqtt_remoteinstance: !include mqtt_remoteinstance.yaml
